<?php

namespace App\Models\Litter\Categories;

use App\Models\Litter\LitterCategory;

class Brand extends LitterCategory
{
    protected $fillable = [
    	'adidas',
        'albertheijn',
        'amazon',
        'aldi',
    	'apple',
        'applegreen',
        'asahi',
        'avoca',

        'ballygowan',
        'bewleys',
        'brambles',
    	'budweiser',
        'bulmers',
        'burgerking',
        'butlers',

        'cadburys',
        'cafe_nero',
        'camel',
        'carlsberg',
        'centra',
    	'coke',
        'circlek',
        'coles',
    	'colgate',
    	'corona',
        'costa',

        'doritos',
        'drpepper',
        'dunnes',
        'duracell',
        'durex',

        'evian',
        'esquires',

        'fosters',
        'frank_and_honest',
    	'fritolay',

        'gatorade',
    	'gillette',
        'guinness',

        'haribo',
    	'heineken',

        'insomnia',

    	'kellogs',
        'kfc',

    	'lego',
        'lidl',
        'lindenvillage',
        'lolly_and_cookes',
    	'loreal',
        'lucozade',

    	'marlboro',
        'mars',
    	'mcdonalds',

        'nero',
        'nescafe',
        'nestle',
    	'nike',

        'obriens',

    	'pepsi',
        'powerade',

    	'redbull',
        'ribena',

    	'samsung',
        'sainsburys',
        'spar',
        'stella',
    	'subway',
        'supermacs',
        'supervalu',
    	'starbucks',

    	'tayto',
        'tesco',
        'thins',

        'volvic',

        'waitrose',
        'walkers',
        'woolworths',
        'wilde_and_greene',
        'wrigleys'
    ];

    public function typesForExport(): array
    {
        return [
            'adidas' => 'adidas',
            'albertheijn' => 'albertheijn',
            'amazon' => 'amazon',
            'aldi' => 'aldi',
            'apple' => 'apple',
            'applegreen' => 'applegreen',
            'asahi' => 'asahi',
            'avoca' => 'avoca',
            'ballygowan' => 'ballygowan',
            'bewleys' => 'bewleys',
            'brambles' => 'brambles',
            'budweiser' => 'budweiser',
            'bulmers' => 'bulmers',
            'burgerking' => 'burgerking',
            'butlers' => 'butlers',
            'cadburys' => 'cadburys',
            'cafe_nero' => 'cafe_nero',
            'camel' => 'camel',
            'carlsberg' => 'carlsberg',
            'centra' => 'centra',
            'coke' => 'coca_cola',
            'circlek' => 'circlek',
            'coles' => 'coles',
            'colgate' => 'colgate',
            'corona' => 'corona',
            'costa' => 'costa',
            'doritos' => 'doritos',
            'drpepper' => 'drpepper',
            'dunnes' => 'dunnes',
            'duracell' => 'duracell',
            'durex' => 'durex',
            'evian' => 'evian',
            'esquires' => 'esquires',
            'fosters' => 'fosters',
            'frank_and_honest' => 'frank_and_honest',
            'fritolay' => 'fritolay',
            'gatorade' => 'gatorade',
            'gillette' => 'gillette',
            'guinness' => 'guinness',
            'haribo' => 'haribo',
            'heineken' => 'heineken',
            'insomnia' => 'insomnia',
            'kellogs' => 'kellogs',
            'kfc' => 'kfc',
            'lego' => 'lego',
            'lidl' => 'lidl',
            'lindenvillage' => 'lindenvillage',
            'lolly_and_cookes' => 'lolly_and_cookes',
            'loreal' => 'loreal',
            'lucozade' => 'lucozade',
            'marlboro' => 'marlboro',
            'mars' => 'mars',
            'mcdonalds' => 'mcdonalds',
            'nero' => 'nero',
            'nescafe' => 'nescafe',
            'nestle' => 'nestle',
            'nike' => 'nike',
            'obriens' => 'obriens',
            'pepsi' => 'pepsi',
            'powerade' => 'powerade',
            'redbull' => 'redbull',
            'ribena' => 'ribena',
            'samsung' => 'samsung',
            'sainsburys' => 'sainsburys',
            'spar' => 'spar',
            'stella' => 'stella',
            'subway' => 'subway',
            'supermacs' => 'supermacs',
            'supervalu' => 'supervalu',
            'starbucks' => 'starbucks',
            'tayto' => 'tayto',
            'tesco' => 'tesco',
            'thins' => 'thins',
            'volvic' => 'volvic',
            'waitrose' => 'waitrose',
            'walkers' => 'walkers',
            'woolworths' => 'woolworths',
            'wilde_and_greene' => 'wilde_and_greene',
            'wrigleys' => 'wrigleys',
        ];
    }
}
