<?php

declare(strict_types=1);

namespace App\Console\Commands\tmp\v5\Migration;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Redis;
use Illuminate\Support\Facades\Schema;

class ResetV5Migration extends Command
{
    /** php artisan olm:v5:reset --force */
    protected $signature   = 'olm:v5:reset {--force : skip confirmation prompt}';
    protected $description = '⚠️  Wipe v5 migration artefacts (photos.*, achievements, photo_tags, Redis metrics)';

    public function handle(): int
    {
        if (!$this->option('force') && !$this->confirm(
                'This will DELETE photo_tags, achievement unlocks and ALL per-user ' .
                'Redis metrics, and will set photos.processed_at / migrated_at = NULL. ' .
                'Continue?'
            )) {
            $this->info('Aborted.');
            return self::SUCCESS;
        }

        /* ------------------------------------------------------------------ */
        /* 1️⃣  Reset columns on photos                                        */
        /* ------------------------------------------------------------------ */
        $updated = DB::table('photos')
            ->update(['processed_at' => null, 'migrated_at' => null]);

        $this->line("• photos table reset ({$updated} rows)");

        /* ------------------------------------------------------------------ */
        /* 2️⃣  Truncate tables generated by the migration run                */
        /* ------------------------------------------------------------------ */
        $tablesToTruncate = [
            'photo_tags',
            'photo_tag_extra_tags',
            'photo_metrics',
            'user_achievements',
        ];

        DB::statement('SET FOREIGN_KEY_CHECKS = 0');
        foreach ($tablesToTruncate as $tbl) {
            if (Schema::hasTable($tbl)) {
                DB::table($tbl)->truncate();
                $this->line("• truncated {$tbl}");
            }
        }
        DB::statement('SET FOREIGN_KEY_CHECKS = 1');

        /* ------------------------------------------------------------------ */
        /* 3️⃣  Flush Redis metrics / streak bitmaps / global hashes          */
        /* ------------------------------------------------------------------ */
        // Adjust the pattern if you use a key-prefix in config/database.php
        Redis::flushdb();
        $this->line("• deleted Redis keys");

        /* ------------------------------------------------------------------ */
        /* 4️⃣  (Optional) flush achievements cache, tag-key cache, etc.      */
        /* ------------------------------------------------------------------ */
        cache()->tags(['achievements', 'tag_key_cache'])->flush();
        $this->line('• cleared achievements / tag-key cache');

        $this->info('✅  v5 migration state has been reset – you can run olm:v5 again.');
        return self::SUCCESS;
    }
}
