const es = {
	cats: {
		Smoking: "Fumar",
		Alcohol: "Alcohol",
		SoftDrinks: "Bebidas",
		Coffee: "Cafe",
		Food: "Comida",
		Coastal: "Costero",
		Brands: "Marcas",
		Other: "Otros",
		Sanitary: "Sanitario",
		Art: "Art",
		TrashDog: "PerroDeBasura"
	},
	reverse: {
		Fumar: "Smoking",
		Alcohol: "Alcohol",
		Comida: "Food",
		Cafe: "Coffee",
		Bebidas: "Soft-Drinks",
		Sanitario: "Sanitary",
		Otros: "Other",
		Costero: "Coastal",
		Art: "Art",
		Marcas: "Brands",
		PerroDeBasura: "TrashDog"
	},
	Fumar: [
		'Colillas de cigarro',
		'Encendedores',
		'Caja de cigarrillos',
		'Bolsa de tabaco',
		'Papel de fumar',
		'Embalaje de plástico',
		'Filtros',
		'Caja de filtro',
		'Fumar (otros)'
	],
	Alcohol: [
		'Botellas de cerveza',
		'Botellas de licores',
		'Botellas de vino',
		'Latas de cerveza',
		'Vidrio roto',
		'Tapas de botellas de cerveza',
		'Embalajes de papel',
		'Embalaje de plástico',
		'Alcohol (otro)'
	],
	Comida: [
		'Envolturas dulces',
		'Empaquetado de papel / cartón',
		'Embalaje de plástico',
		'Cubiertos de plástico',
		'Paquete Crisp / Chip (pequeño)',
		'Paquete Crisp / Chip (grande)',
		'Espuma de poliestireno',
		'Servilletas',
		'Paquete de salsa',
		'Jarra de vidrio',
		'Tapa de jarra de vidrio',
		'Comida (otros)'
	],
	Cafe: [
		'Taza de café',
		'Tapas de café',
		'Café (otro)'
	],
	Bebidas: [
		'Botella de agua plástica',
		'Botella plástica de bebida gaseosa',
		'Lata (bebida gaseosa)',
		'Tapas de botellas',
		'Etiquetas de botellas',
		'Botella de bebida deportiva',
		'Pajitas',
		'Copas de plástico',
		'Tapas de plástico',
		'Botella de leche',
		'Cartón de leche',
		'Copas de papel',
		'Cajas de jugo',
		'Botellas de jugo',
		'Paquete de jugo',
		'Botellas de té',
		'Lata de Té',
		'Lata de bebida de energía',
		'Refresco (otro)'
	],
	Sanitario: [
		'Condones',
		'Pañales',
		'Menstrual',
		'Desodorante',
		'Hisopos de oído',
		'Palillo de dientes',
		'Cepillo de dientes',
		'Sanitario (otros)'
	],
	Otros: [
		'Mierda de perro',
		'Plástico no identificado',
		'Basurero Grande / Variado',
		'Objeto de metal',
		'Bolsas de plástico',
		'Carteles electorales',
		'Carteles de Venta',
		'Libros',
		'Revistas',
		'Papel',
		'Estacionario',
		'Botella de lavado',
		'Liga para el cabello',
		'Ear Plugs (música)',
		'Otro (otro)'
	],
	Costero: [
		'Microplasticos',
		'Plásticos medianos',
		'Macro plásticos',
		'Cuerda/soga pequeña',
		'Cuerda/soga mediana',
		'Cuerda/soga grande',
		'Articulos de pesca',
		'Boyas',
		'Botella de plástico degradado',
		'Bolsa de plástico degradado',
		'Pajitas de beber degradadas',
		'Encendedores degradados',
		'Globos',
		'Lego',
		'Cartuchos de escopeta',
		'Costero (otro)'
	],
	Art: [
		'Art'
	],
	Marcas: [
        "Adidas",
        "Amazon",
        "Aldi",
        "Apple",
        "Applegreen",
        "Asahi",
        "Avoca",
        "Ballygowan",
        "Bewleys",
        "Brambles",
        "Budweiser",
        "Bulmers",
        "BurgerKing",
        "Butlers",
        "Cafe-Nero",
        "Cadburys",
        "Carlsberg",
        "Centra",
        "CircleK",
        "Coca-Cola",
        "Colgate",
        "Coles",
        "Corona",
        "Costa",
        "Doritos",
        "DrPepper",
        "Dunnes",
        "Duracell",
        "Durex",
        "Esquires",
        "Evian",
        "Fosters",
        "Frank-and-Honest",
        "Frito-Lay",
        "Gatorade",
        "Gillette",
        "Guinness",
        "Haribo",
        "Heineken",
        "Insomnia",
        "Kellogs",
        "KFC",
        "Lego",
        "Lidl",
        "LindenVillage",
        "Lolly-and-Cookes",
        "Loreal",
        "Lucozade",
        "Nero",
        "Nescafe",
        "Nestle",
        "Marlboro",
        "Mars",
        "McDonalds",
        "Nike",
        "O-Briens",
        "Pepsi",
        "Powerade",
        "Redbull",
        "Ribena",
        "Samsung",
        "Sainsburys",
        "Spar",
        "Starbucks",
        "Stella",
        "Subway",
        "Supermacs",
        "Supervalu",
        "Tayto",
        "Tesco",
        "Thins",
        "Volvic",
        "Waitrose",
        "Wilde-and-Greene",
        "Woolworths",
        "Wrigleys"
	],
	PerroDeBasura: [
		"PerroYBasura",
        "Littercat",
        "LitterDuck"
	]

}

export { es };