const fr = {
	cats: {
		Smoking: "Cigarette",
        Alcohol: "Alcool",
        Brands: "Marques",
        Coastal: "Côtier",
        Coffee: "Café",
		Food: "Nourriture",
		SoftDrinks: "Boisson",
		Sanitary: "Hygiène",
		Other: "Autres",
		Art: "Art",
		TrashDog: "TrashDog"
	},
    reverse: {
        Cigarette: "Smoking",
        Alcool: "Alcohol",
        Nourriture: "Food",
        Café: "Coffee",
        Boisson: "SoftDrinks",
        Hygiène: "Sanitary",
        Autres: "Other",
        Côtier: "Coastal",
        Art: "Art",
        Marques: "Brands",
        TrashDog: "TrashDog"
    },
	Cigarette: [
		"Mégot de cigarette",
		"Briquet",
		"Boîte de cigarettes",
		"Boîte/Sachet de tabac",
		"Emballage en plastique",
		"Filtre",
		"Boîte de filtres",
		"Cigarette (autre)",
	],
    Marques: [
        "Adidas",
        "Amazon",
        "Aldi",
        "Apple",
        "Applegreen",
        "Asahi",
        "Avoca",
        "Ballygowan",
        "Bewleys",
        "Brambles",
        "Budweiser",
        "Bulmers",
        "BurgerKing",
        "Butlers",
        "Cafe-Nero",
        "Cadburys",
        "Carlsberg",
        "Centra",
        "CircleK",
        "Coca-Cola",
        "Colgate",
        "Coles",
        "Corona",
        "Costa",
        "Doritos",
        "DrPepper",
        "Dunnes",
        "Duracell",
        "Durex",
        "Esquires",
        "Evian",
        "Fosters",
        "Frank-and-Honest",
        "Frito-Lay",
        "Gatorade",
        "Gillette",
        "Guinness",
        "Haribo",
        "Heineken",
        "Insomnia",
        "Kellogs",
        "KFC",
        "Lego",
        "Lidl",
        "LindenVillage",
        "Lolly-and-Cookes",
        "Loreal",
        "Lucozade",
        "Nero",
        "Nescafe",
        "Nestle",
        "Marlboro",
        "Mars",
        "McDonalds",
        "Nike",
        "O-Briens",
        "Pepsi",
        "Powerade",
        "Redbull",
        "Ribena",
        "Samsung",
        "Sainsburys",
        "Spar",
        "Starbucks",
        "Stella",
        "Subway",
        "Supermacs",
        "Supervalu",
        "Tayto",
        "Tesco",
        "Thins",
        "Volvic",
        "Waitrose",
        "Wilde-and-Greene",
        "Woolworths",
        "Wrigleys"
    ],
	Nourriture: [
        "Emballage de bonbons",
        "Emballage en papier/carton",
        "Emballage en plastique",
        "Couverts en plastique",
        "Paquet de chips (petit)",
        "Paquet de chips (grand)",
        "Polystyrène",
        "Serviette en papier",
        "Paquet de sauce",
        "Bocal en verre",
        "Couvercle de bocal",
        "Nourriture (autre)"
	],
	Café: [
        "Tasse de café",
        "Couvercle",
        "Café (autre)"
    ],
	Alcool: [
	    "Bouteille en verre (bière)",
	    "Bouteille en verre (alcool fort)",
	    "Bouteille en verre (vin)",
	    "Cannette de bière",
	    "Verre brisé",
	    "Bouchon de bouteille",
	    "Emballage en papier",
	    "Emballage plastique",
	    "Alcool (autre)"
	],
	Boisson: [
        "Bouteille d`eau en plastique",
        "Bouteille de soda",
        "Cannette de soda",
        "Bouchon de bouteille",
        "Label pada Botol",
        "Bouteille de boissons énergétique",
        "Pailles",
        "Tasse en plastique",
        "Couvercle de tasse en plastique",
        "Bouteille/Brique de lait (plastique)",
        "Bouteille/Brique de lait (carton)",
        "Verre en carton",
        "Brique de jus (carton)",
        "Bouteille de jus",
        "Emballage de jus",
        "Bouteille d`Ice Tea",
        "Cannette d`Ice Tea",
        "Cannette de boisson énergisante",
        "Boissons (autre)"
    ],
    Hygiène: [
	    "Préservatif",
	    "Couche pour bébé",
	    "Serviettes hygiéniques",
	    "Déodorant",
	    "Coton-tige",
	    "Cure-dent",
	    "Brosse à dents",
	    "Hygiène (autre)"
    ],
	Autres: [
		"Crotte de chien",
		"Plastique non identifiable",
		"Décharge illégale",
		"Objet métallique",
		"Sac en plastique",
		"Affiches élections",
		"Affiche a vendre",
		"Livre",
		"Magazine",
		"Papier",
		"Papier à lettres",
		"Bouteille de détergent",
		"Elastique à cheveux",
		"Ecouteurs",
		"Autre (autre)"
    ],
    Côtier: [
        "Microplastiques",
        "Plastique (moyen)",
        "Plastique (grand)",
        "Ficelle",
        "Corde",
        "Cordage",
        "Filet de pêche",
        "Bouée",
        "Bouteille en plastique (dégradée)",
        "Sac en plastique (dégradé)",
        "Paille (dégradée)",
        "Briquet (dégradé)",
        "Ballon",
        "Lego",
        "Balle de fusil, cartouche",
        "Côtier (autre)"
    ],
    Art: [
	    "Item"
	],
	TrashDog: [
	    "TrashDog",
        "Littercat",
        "LitterDuck"
	],
}

export { fr };