const ie = {
	cats: {
		Smoking: "Tobac",
        Alcohol: "Alcól",
        Brands: "Brands",
        Coastal: "Trá",
        Coffee: "Caife",
		Food: "Bia",
		SoftDrinks: "SoftDrinks",
		Sanitary: "Sláintíoch",
		Other: "Eile",
		Art: "Ealaíon",
		TrashDog: "TrashDog"
	},
	Tobac: [
		"Toitíní",
		"Lastóirí ",
		"Bosca Toitíní",
		"Mála Tobac",
		"Pacáistíocht phlaisteach",
		"Scagairí",
		"Bosca Scagairí ",
		"Tobac (eile)",
	],
    Brands: [
        "Adidas",
        "Amazon",
        "Aldi",
        "Apple",
        "Applegreen",
        "Asahi",
        "Avoca",
        "Ballygowan",
        "Bewleys",
        "Brambles",
        "Budweiser",
        "Bulmers",
        "BurgerKing",
        "Butlers",
        "Cafe-Nero",
        "Cadburys",
        "Carlsberg",
        "Centra",
        "CircleK",
        "Coca-Cola",
        "Colgate",
        "Coles",
        "Corona",
        "Costa",
        "Doritos",
        "DrPepper",
        "Dunnes",
        "Duracell",
        "Durex",
        "Esquires",
        "Evian",
        "Fosters",
        "Frank-and-Honest",
        "Frito-Lay",
        "Gatorade",
        "Gillette",
        "Guinness",
        "Haribo",
        "Heineken",
        "Insomnia",
        "Kellogs",
        "KFC",
        "Lego",
        "Lidl",
        "LindenVillage",
        "Lolly-and-Cookes",
        "Loreal",
        "Lucozade",
        "Nero",
        "Nescafe",
        "Nestle",
        "Marlboro",
        "Mars",
        "McDonalds",
        "Nike",
        "O-Briens",
        "Pepsi",
        "Powerade",
        "Redbull",
        "Ribena",
        "Samsung",
        "Sainsburys",
        "Spar",
        "Starbucks",
        "Stella",
        "Subway",
        "Supermacs",
        "Supervalu",
        "Tayto",
        "Tesco",
        "Thins",
        "Volvic",
        "Waitrose",
        "Wilde-and-Greene",
        "Woolworths",
        "Wrigleys"
    ],
	Bia: [
        "Clúdaigh milseáin",
        "Pacáistíocht chairtchláir/pháipéir",
        "Pacáistíocht phlaisteach",
        "Sceanra plaisteach",
        "Paicéad briosc (beag)",
        "Paicéad brios (mór)",
        "Styrofoam",
        "Naipcíní",
        "Paicéad anlainn",
        "Searróg ghloine",
        "Glass Jar Lid",
        "Bia (eile)"
	],
	Caife: [
        "Cupáin Caife",
        "Clúdaigh chaife",
        "Caife (eile)"
    ],
	Alcól: [
	    "Buidéil ghloine (Beoir)",
	    "Buidéil ghloine (Biotáille)",
	    "Buidéil ghloine",
	    "Cannaí Beorach",
	    "Gloine briste",
	    "Beer bottle tops",
	    "Pacáistíocht Páipéir",
	    "pacáistíocht Phlaisteach",
	    "Alcól (eile)"
	],
	SoftDrinks: [
        "Plastic Water bottle",
        "Plastic Fizzy Drink bottle",
        "Tin can (fizzy drink)",
        "Bottle Tops",
        "Bottle Labels",
        "Sports Drink bottle",
        "Straws",
        "Plastic Cups",
        "Plastic Cup Tops",
        "Milk Bottle",
        "Milk Carton",
        "Paper Cups",
        "Juice Cartons",
        "Juice Bottles",
        "Juice Packet",
        "Ice Tea Bottles",
        "Ice Tea Can",
        "Energy Can",
        "Soft Drink (other)"
    ],
     Sláintíoch: [
	    "Coiscíní",
	    "Clúidíní Linbh",
	    "Earra Míosta",
	    "Díbholaíoch",
	    "Maipíní Cluaise",
	    "Bior fiacla",
	    "Scuab fiacla",
	    "Sláintíoch (eile)"
    ],
	Other: [
		"Dogshit",
		"Unidentified Plastic",
		"Large/Random Dump",
		"Metal Object",
		"Plastic Bags",
		"Election Posters",
		"For Sale Posters",
		"Books",
		"Magazines",
		"Paper",
		"Stationary",
		"Washing-up Bottle",
		"Hair Tie",
		"Ear Plugs (music)",
		"Other (other)"
    ],
    Coastal: [
        "Microplastics",
        "Mediumplastics",
        "Macroplastics",
        "Rope small",
        "Rope medium",
        "Rope large",
        "Fishing gear/nets",
        "Buoys",
        "Degraded Plastic Bottle",
        "Degraded Plastic Bag",
        "Degraded Drinking Straws",
        "Degraded Lighters",
        "Balloons",
        "Lego",
        "Shotgun Cartridges",
        "Coastal (other)"
    ],
    Art: [
	    "Item"
	],
	TrashDog: [
	    "TrashDog",
        "Littercat",
        "LitterDuck"
	],
}

export { ie };