<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /**
     * Move any existing custom_tag_primary_id values from photo_tags into photo_tag_extra_tags.
     *
     * In practice, fresh v5 data is generated by the migration script so existing data
     * will be recreated. This migration handles any stragglers that might exist.
     */
    public function up(): void
    {
        // Copy any remaining custom_tag_primary_id values to extra_tags
        DB::statement("
            INSERT INTO photo_tag_extra_tags (photo_tag_id, tag_type, tag_type_id, quantity, created_at, updated_at)
            SELECT id, 'custom_tag', custom_tag_primary_id, 1, NOW(), NOW()
            FROM photo_tags
            WHERE custom_tag_primary_id IS NOT NULL
            AND NOT EXISTS (
                SELECT 1 FROM photo_tag_extra_tags pte
                WHERE pte.photo_tag_id = photo_tags.id
                AND pte.tag_type = 'custom_tag'
                AND pte.tag_type_id = photo_tags.custom_tag_primary_id
            )
        ");

        // NULL out migrated values
        DB::update('UPDATE photo_tags SET custom_tag_primary_id = NULL WHERE custom_tag_primary_id IS NOT NULL');
    }

    public function down(): void
    {
        // No-op: column still exists at this point, next migration drops it.
    }
};
