<?php

return [
    'titles' => [
        1  => 'Beginner',
        2  => 'Observer',
        3  => 'Field Observer',
        4  => 'Recorder',
        5  => 'Field Recorder',
        6  => 'Surveyor',
        7  => 'Field Surveyor',
        8  => 'Mapper',
        9  => 'Field Mapper',
        10 => 'Contributor',
        11 => 'Data Contributor',
        12 => 'Researcher',
        13 => 'Field Researcher',
        14 => 'Analyst',
        15 => 'Data Analyst',
        16 => 'Specialist',
        17 => 'Environmental Specialist',
        18 => 'Scientist',
        19 => 'Citizen Scientist',
        20 => 'Senior Scientist',
        21 => 'Lead Scientist',
        22 => 'Expert',
        23 => 'Senior Expert',
        24 => 'Advisor',
        25 => 'Senior Advisor',
        26 => 'Director',
        27 => 'Regional Director',
        28 => 'National Director',
        29 => 'International Director',
        30 => 'Ambassador',
        31 => 'Senior Ambassador',
        32 => 'Global Ambassador',
        33 => 'Fellow',
        34 => 'Senior Fellow',
        35 => 'Distinguished Fellow',
        36 => 'Champion',
        37 => 'National Champion',
        38 => 'Global Champion',
        39 => 'Pioneer',
        40 => 'Trailblazer',
        41 => 'Visionary',
        42 => 'Guardian',
        43 => 'Earth Guardian',
        44 => 'Steward',
        45 => 'Earth Steward',
        46 => 'Luminary',
        47 => 'Icon',
        48 => 'Legend',
        49 => 'Grandmaster',
        50 => 'Founder',
    ],

    'base_xp' => 100,
    'growth_factor' => 1.5,
    'max_level' => 50,
];
