<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Tag Usage Counts File
    |--------------------------------------------------------------------------
    |
    | Path to the committed JSON file holding the all-time count of recorded
    | tags per (litter_object, category, type). It is regenerated by hand with
    | `php artisan olm:rebuild-tag-counts` and read by GetTagsController to
    | embed the counts map in the /api/tags/all response. This is the single
    | source of truth for the path so both the writer (command) and reader
    | (controller) stay in sync, and so tests can point it at a temp file.
    |
    */
    'usage_counts_path' => resource_path('data/tag_usage_counts.json'),

    /*
    |--------------------------------------------------------------------------
    | Public Tag Counts File
    |--------------------------------------------------------------------------
    |
    | Path to the committed JSON file holding the public-facing count of
    | recorded tags, scoped to photos visible on the public map
    | (`is_public = 1 AND verified >= 2`). Regenerated by hand with
    | `php artisan olm:rebuild-tag-counts --scope=public` and read by
    | GetTagsController to serve the /api/tags/most-tagged ranking. Kept at the
    | same (object, category, type) granularity as the internal file so the two
    | are diffable row-for-row. Separate from the internal total so both numbers
    | stay transparent and auditable.
    |
    */
    'public_counts_path' => resource_path('data/tag_counts_public.json'),
];
