const it = {
	cats: {
        Alcohol: "Alcool",
        Art: "Arte",
        Brands: "Marche",
        Coastal: "Costiero",
        Coffee: "Caffe",
		Food: "Cibo",
        Other: "Altra",
		Sanitary: "Sanitaria",
        Smoking: "Fumo",
        SoftDrinks: "Bevande",
		TrashDog: "TrashDog"
	},
    reverse: {
        Fumo: "Smoking",
        Alcool: "Alcohol",
        Cibo: "Food",
        Caffe: "Coffee",
        Bevande: "SoftDrinks",
        Sanitaria: "Sanitary",
        Altra: "Other",
        Costiero: "Coastal",
        Arte: "Art",
        Marche: "Brands",
        TrashDog: "TrashDog"
    },
	Fumo: [
		"Sigarette/Mozziconi",
		"Accendini",
		"Scatole di sigarette",
		"Buste per il tabacco",
        "Cartine",
		"Imballaggi in plastica",
		"Filtri",
		"Scatole dei filtri",
		"Fumo (altro)",
	],
    Marche: [
        "Adidas",
        "Amazon",
        "Aldi",
        "Apple",
        "Applegreen",
        "Asahi",
        "Avoca",
        "Ballygowan",
        "Bewleys",
        "Brambles",
        "Budweiser",
        "Bulmers",
        "BurgerKing",
        "Butlers",
        "Cadburys",
        "Cafe-Nero",
        "Camel",
        "Carlsberg",
        "Centra",
        "CircleK",
        "Coca-Cola",
        "Colgate",
        "Coles",
        "Corona",
        "Costa",
        "Doritos",
        "DrPepper",
        "Dunnes",
        "Duracell",
        "Durex",
        "Esquires",
        "Evian",
        "Fosters",
        "Frank-and-Honest",
        "Frito-Lay",
        "Gatorade",
        "Gillette",
        "Guinness",
        "Haribo",
        "Heineken",
        "Insomnia",
        "Kellogs",
        "KFC",
        "Lego",
        "Lidl",
        "LindenVillage",
        "Lolly-and-Cookes",
        "Loreal",
        "Lucozade",
        "Nero",
        "Nescafe",
        "Nestle",
        "Marlboro",
        "Mars",
        "McDonalds",
        "Nike",
        "O-Briens",
        "Pepsi",
        "Powerade",
        "Redbull",
        "Ribena",
        "Samsung",
        "Sainsburys",
        "Spar",
        "Starbucks",
        "Stella",
        "Subway",
        "Supermacs",
        "Supervalu",
        "Tayto",
        "Tesco",
        "Thins",
        "Volvic",
        "Waitrose",
        "Wilde-and-Greene",
        "Woolworths",
        "Wrigleys"
    ],
	Cibo: [
        "Involucri di dolci",
        "Confezioni di carta/cartone",
        "Confezioni di plastica",
        "Posate di plastica",
        "Pacchetti di patatine (piccoli)",
        "Pacchetti di patatine (grandi)",
        "Polistirolo",
        "Tovaglioli",
        "Bustine di salse",
        "Vasetti di vetro",
        "Coperchi per vasetti di vetro",
        "Cibo (altro)"
	],
	Caffe: [
        "Tazza di caffe",
        "Coperchi di caffe",
        "Caffe (altro)"
    ],
	Alcool: [
        "Caffe (altro)",
	    "Bottiglie di vetro (birra)",
	    "Bottiglie di vetro (superalcolici)",
	    "Bottiglie di vetro (vino)",
	    "Vetro rotto",
	    "Tappi di bottiglie di birra",
	    "Confezioni di carta",
	    "Confezioni di plastica",
        "Pinte di vetro",
	    "Alcolici (altro)"
	],
	Bevande: [
        "Bottiglie d’acqua plastica",
        "Bottiglie bevande gassate",
        "Lattine",
        "Linguette delle lattine",
        "Tappi di bottiglie",
        "Etichette di bottiglie",
        "Bottiglie energetiche",
        "Cannucce",
        "Confezioni di cannucce",
        "Bicchieri di plastica",
        "Coperchi per bicchieri di plastica",
        "Bottiglie di latte",
        "Tetrapak di latte",
        "Bicchieri di carta",
        "Tetrapak di succhi",
        "Bottiglie di succhi",
        "Pacchetti di succo",
        "Bottiglie di tè freddo",
        "Lattine di tè freddo",
        "Lattine di bevande energetiche",
        "Bicchieri di polistirolo",
        "Bibite analcoliche (altro)"
    ],
    Sanitaria: [
	    "Preservativi",
        "Pannolini",
        "Assorbenti",
	    "Deodoranti",
	    "Cotton fioc",
	    "Stuzzicadenti",
	    "Spazzolini",
        "Salviette umidificate",
	    "Igiene (altro)"
    ],
	Altra: [
        "Discarica illegale",
        "Cacca di cane",
		"Cacca di cane in busta",
		"Plastica non identificata",
        "Coni stradali",
        "Plastica non identificata",
		"Oggetti di metallo",
		"Buste di plastica",
        "Parti di automobili",
        "Palloncini",
        "Pile",
        "Vestiario",
		"Manifesti elettorali",
		"Manifesti di vendita",
		"Libri",
		"Riviste",
		"Carta",
		"Articoli di cancelleria",
		"Bottiglie di detersivi",
		"Elastici per capelli",
		"Auricolari",
        "Rottami elettronici (piccoli)",
        "Rottami elettronici (grandi)",
		"Altro (altro)"
    ],
    Costiero: [
        "Microplastiche",
        "Plastica di medie dimensioni",
        "Macroplastica",
        "Corde (piccole)",
        "Corde (medie)",
        "Corde (grande)",
        "Attrezzi da pesca/reti",
        "Polistirolo (piccolo)",
        "Polistirolo (medio)",
        "Polistirolo (grande)",
        "Boe",
        "Bottiglie di plastica degradate",
        "Sacchetti di plastica degradati",
        "Cannucce degradate",
        "Accendini degradati",
        "Palloni",
        "Lego",
        "Cartucce per fucili",
        "Costiere (altro)"
    ],
    Arte: [
	    "Item"
	],
	TrashDog: [
	    "TrashDog",
        "Littercat",
        "LitterDuck"
	],
}

export { it };