const ms = {
	cats: {
		Smoking: "Rokok",
        Alcohol: "Alkohol",
        Brands: "Brands",
        Coastal: "Pantai",
        Coffee: "Kopi",
		Food: "Makanan",
		SoftDrinks: "MinumanRingan",
		Sanitary: "ProdukPenjagaanDiri",
		Other: "Lainlain",
		Art: "Seni",
		TrashDog: "TrashDog"
	},
    reverse: {
        Rokok: "Smoking",
        Alkohol: "Alcohol",
        Makanan: "Food",
        Kopi: "Coffee",
        MinumanRingan: "Soft-Drinks",
        ProdukPenjagaanDiri: "Sanitary",
        Lainlain: "Other",
        Pantai: "Coastal",
        Seni: "Art",
        Marcas: "Brands",
        PerroDeBasura: "TrashDog"
    },
	Rokok: [
		"Rokok",
		"Pemetik Api",
		"Kertas Gulung Tembakau",
		"Uncang Tembakau",
		"Plastik Pembungkus",
		"Penapis",
		"Kotak Penapis",
		"Rokok (lain-lain)",
	],
    Brands: [
        "Adidas",
        "Amazon",
        "Aldi",
        "Apple",
        "Applegreen",
        "Asahi",
        "Avoca",
        "Ballygowan",
        "Bewleys",
        "Brambles",
        "Budweiser",
        "Bulmers",
        "BurgerKing",
        "Butlers",
        "Cafe-Nero",
        "Cadburys",
        "Carlsberg",
        "Centra",
        "CircleK",
        "Coca-Cola",
        "Colgate",
        "Coles",
        "Corona",
        "Costa",
        "Doritos",
        "DrPepper",
        "Dunnes",
        "Duracell",
        "Durex",
        "Esquires",
        "Evian",
        "Fosters",
        "Frank-and-Honest",
        "Frito-Lay",
        "Gatorade",
        "Gillette",
        "Guinness",
        "Haribo",
        "Heineken",
        "Insomnia",
        "Kellogs",
        "KFC",
        "Lego",
        "Lidl",
        "LindenVillage",
        "Lolly-and-Cookes",
        "Loreal",
        "Lucozade",
        "Nero",
        "Nescafe",
        "Nestle",
        "Marlboro",
        "Mars",
        "McDonalds",
        "Nike",
        "O-Briens",
        "Pepsi",
        "Powerade",
        "Redbull",
        "Ribena",
        "Samsung",
        "Sainsburys",
        "Spar",
        "Starbucks",
        "Stella",
        "Subway",
        "Supermacs",
        "Supervalu",
        "Tayto",
        "Tesco",
        "Thins",
        "Volvic",
        "Waitrose",
        "Wilde-and-Greene",
        "Woolworths",
        "Wrigleys"
    ],
	Makanan: [
        "Pembalut gula-gula",
        "Pembungkus Kertas/Kadbod",
        "Pembungkus Plastik",
        "Kutleri Plastik",
        "Paket Kerepek/Keropok (kecil)",
        "Paket Kerepek/Keropok (besar)",
        "Styrofom/Polystyrene",
        "Kertas Tisu",
        "Paket Sos",
        "Bekas gelas",
        "Penutup bekas gelas",
        "Makanan (lain-lain)"
	],
	Kopi: [
        "Cawan kopi",
        "Penutup cawan",
        "Kopi (lain-lain)"
    ],
	Alkohol: [
	    "Botol Gelas (bir)",
	    "Botol Gelas (spirit)",
	    "Botol Gelas (wain)",
	    "Tin Bir",
	    "Serpihan Gelas",
	    "Penutup Botol Bir",
	    "Pembungkus kertas",
	    "Pembungkus plastik",
	    "Alkohol (lain-lain)"
	],
	MinumanRingan: [
        "Botol Air Minuman/Mineral Plastik",
        "Botol Minuman Berkarbonat",
        "Tin Aluminium",
        "Penutup Botol",
        "Label pada Botol",
        "Botol Minuman Sukan/Isotonik",
        "Penyedut Minuman",
        "Cawan Plastik Pakai Buang",
        "Penutup Cawan Plastik Pakai Buang",
        "Botol Susu",
        "Karton/Kotak Susu",
        "Cawan Kertas",
        "Karton/Kotak Jus",
        "Botol Jus",
        "Paket Jus",
        "Botol Teh Ais",
        "Tin Aluminium Teh Ais",
        "Tin Aluminium Minuman Tenaga",
        "Minuman Ringan (lain-lain)"
    ],
    ProdukPenjagaanDiri: [
	    "Kondom",
	    "Lampin bayi",
	    "Produk Penjagaan Wanita",
	    "Deodoran",
	    "Putik Kapas",
	    "Pencungkil Gigi",
	    "Berus Gigi",
	    "Produk Penjagaan Diri (lain-lain)"
    ],
	Lainlain: [
		"Tahi Anjing",
		"Plastik yang tak dapat dikenalpasti",
		"Sampah Pukal/Tempat Pembuangan Sampah",
		"Objek logam",
		"Beg Plastik",
		"Poster Pilihan Raya",
		"Poster Jualan",
		"Buku",
		"Majalah",
		"Kertas",
		"Alat Tulis",
		"Botol Bahan Pencuci",
		"Pengikat Rambut",
		"Earphone (muzik)",
		"Lain (lain-lain)"
    ],
    Pantai: [
        "Mikroplastik",
        "Partikel Plastik",
        "Makroplastik",
        "Tali halus",
        "Tali sederhana",
        "Tali tebal",
        "Alatan memancing/pukat",
        "Boya",
        "Serpihan Botol Plastik",
        "Cebisan Beg Plastik",
        "Cebisan Penyedut Minuman",
        "Pemetik Api",
        "Belon",
        "Lego",
        "Kelongsong Peluru",
        "Pantai (lain-lain)"
    ],
    Seni: [
	    "Seni"
	],
	TrashDog: [
	    "Anjing Pengutip Sampah",
        "Littercat",
        "LitterDuck"
	],
}

export { ms };