const tk = {
	cats: {
		Smoking: "Sigara",
        Alcohol: "Alkol",
        Brands: "Brands",
        Coastal: "Kıyısal",
        Coffee: "Kahve",
		Food: "GıdaMaddesi",
		SoftDrinks: "AlkolsüzIçecekler",
		Sanitary: "Hijyen",
		Other: "Diğer",
		Art: "Sanat",
		TrashDog: "TrashDog"
	},
    reverse: {
        Sigara: "Smoking",
        Alkol: "Alcohol",
        Marcas: "Brands",
        Comida: "Food",
        Kahve: "Coffee",
        AlkolsüzIçecekler: "Soft-Drinks",
        Hijyen: "Sanitary",
        Diğer: "Other",
        Kıyısal: "Coastal",
        Sanat: "Art",
        TrashDog: "TrashDog"
    },
	Sigara: [
		"Sigara/İzmarit",
		"Çakmak",
		"Sigara Kutusu",
		"Tütün paketi",
		"Plastik Ambalaj",
		"Sigara filtresi",
		"Sigara filtre kutusu",
		"Sigara (diğer)",
	],
    Brands: [
               "Adidas",
        "Amazon",
        "Aldi",
        "Apple",
        "Applegreen",
        "Asahi",
        "Avoca",
        "Ballygowan",
        "Bewleys",
        "Brambles",
        "Budweiser",
        "Bulmers",
        "BurgerKing",
        "Butlers",
        "Cafe-Nero",
        "Cadburys",
        "Carlsberg",
        "Centra",
        "CircleK",
        "Coca-Cola",
        "Colgate",
        "Coles",
        "Corona",
        "Costa",
        "Doritos",
        "DrPepper",
        "Dunnes",
        "Duracell",
        "Durex",
        "Esquires",
        "Evian",
        "Fosters",
        "Frank-and-Honest",
        "Frito-Lay",
        "Gatorade",
        "Gillette",
        "Guinness",
        "Haribo",
        "Heineken",
        "Insomnia",
        "Kellogs",
        "KFC",
        "Lego",
        "Lidl",
        "LindenVillage",
        "Lolly-and-Cookes",
        "Loreal",
        "Lucozade",
        "Nero",
        "Nescafe",
        "Nestle",
        "Marlboro",
        "Mars",
        "McDonalds",
        "Nike",
        "O-Briens",
        "Pepsi",
        "Powerade",
        "Redbull",
        "Ribena",
        "Samsung",
        "Sainsburys",
        "Spar",
        "Starbucks",
        "Stella",
        "Subway",
        "Supermacs",
        "Supervalu",
        "Tayto",
        "Tesco",
        "Thins",
        "Volvic",
        "Waitrose",
        "Wilde-and-Greene",
        "Woolworths",
        "Wrigleys"
    ],
	GıdaMaddesi: [
        "Tatlı abur cubur ambalajı",
        "Kağıt/karton ambalaj",
        "Plastik ambalaj",
        "Plastik çatal bıçak",
        "Cips paketi (küçük)",
        "Cips paketi (büyük)",
        "Köpük",
        "Peçete",
        "Sos paketi",
        "Cam şişe",
        "Cam şişe kapağı",
        "Gıda (diğer)"
	],
	Kahve: [
        "Kahve bardağı",
        "Kahve bardağı kapağı",
        "Kahve (diğer)"
    ],
	Alkol: [
	    "Bira (Cam Şişe)",
	    "Alkollü içkiler (cam şişe)",
	    "Şarap (cam şişe)",
	    "Bira kutusu",
	    "Kırık cam",
	    "Bira şişesi kapağı",
	    "Kağıt ambalaj",
	    "Plastik ambalaj",
	    "Alkol (diğer)"
	],
	AlkolsüzIçecekler: [
        "Plastik su şişesi",
        "Plastik gazlı içecek şişesi",
        "Teneke gazlı içecek kutusu",
        "Şişe kapağı",
        "Şişe marka etiketi",
        "Sporcu içeceği şişesi",
        "Pipet",
        "Plastik bardak",
        "Plastik bardak kapağı",
        "Şüt şişesi",
        "Süt kartonu",
        "Karton bardak",
        "Meyve suyu kartonu",
        "Meyve suyu şişesi",
        "Meyve suyu paketi",
        "Soğu çay şişesi",
        "Teneke soğuk çay",
        "Enerji içeceği tenekesi",
        "Alkolsüz içecekler (diğer)"
    ],
     Hijyen: [
	    "Condoms",
	    "Nappies",
	    "Menstral",
	    "Deodorant",
	    "Ear Swabs",
	    "Tooth Pick",
	    "Tooth Brush",
	    "Sanitary (other)"
    ],
	Diğer: [
		"Köpek dışkısı",
		"Tanımlanamayan plastik",
		"Çöp yığını",
		"Metal obje",
		"Plastik poşet",
		"Seçim afişi",
		"İndirim afişi",
		"Kitap",
		"Dergi",
		"Kağıt",
		"Stasyoner",
		"Bulaşık deterjanı şişesi",
		"Saç tokası",
		"Müzik dinleme kulaklığı",
		"Diğer (Diğer)"
    ],
    Kıyısal: [
        "Mikroplastik",
        "Medyum plastik",
        "Makroplastik",
        "Kısa halat",
        "Orta boy halat",
        "Uzun halat",
        "Balıkçı ağı",
        "Şamandra",
        "Parçalanmaya yüz tutmuş plastik şişe",
        "Parçalanmaya yüz tutmuş plastik poşet",
        "Parçalanmaya yüz tutmuş plastik pipet",
        "Parçalanmaya yüz tutmuş çakmak",
        "Balon",
        "Lego",
        "Ateşli silah fişeği",
        "Kıyısal (Diğer)"
    ],
    Sanat: [
	    "Sanat"
	],
	TrashDog: [
	    "Köpek çöp kutusu",
        "Littercat",
        "LitterDuck"
	],
}

export { tk };